apiVersion: v1
kind: Pod
metadata:
  name: "secure-monolith"
  labels:
    app: monolith
spec:
  containers:
    # - name: nginx
    #   image: "nginx:1.9.14"
    #   lifecycle:
    #     preStop:
    #       exec:
    #         command: ["/usr/sbin/nginx","-s","quit"]
    #   volumeMounts:
    #     - name: "nginx-proxy-conf"
    #       mountPath: "/etc/nginx/conf.d"
    #     - name: "tls-certs"
    #       mountPath: "/etc/tls"
    - name: monolith
      image: "asia.gcr.io/instant-matter-785/https-server"
      ports:
        - name: http
          containerPort: 3000
        - name: https
          containerPort: 3001
        - name: health
          containerPort: 3000
      volumeMounts:
        - name: "tls-certs"
          mountPath: "/opt/tls"
      resources:
        limits:
          cpu: 0.2
          memory: "200Mi"
      livenessProbe:
        httpGet:
          path: /healthz
          port: 3000
          scheme: HTTP
        initialDelaySeconds: 5
        periodSeconds: 15
        timeoutSeconds: 5
      readinessProbe:
        httpGet:
          path: /readiness
          port: 3000
          scheme: HTTP
        initialDelaySeconds: 5
        timeoutSeconds: 1
  volumes:
    - name: "tls-certs"
      secret:
        secretName: "tls-certs"
    # - name: "nginx-proxy-conf"
    #   configMap:
    #     name: "nginx-proxy-conf"
    #     items:
    #       - key: "proxy.conf"
    #         path: "proxy.conf"
