apiVersion: v1
kind: Pod
metadata:
  name: "httpbin"
  labels:
    app: httpbin
spec:
  containers:
    - name: httpbin
      image: "asia.gcr.io/instant-matter-785/httpbin:latest"
      ports:
        - name: http
          containerPort: 8000
